"""init schema 7 tables

Revision ID: 5b5f2728ce43
Revises: 
Create Date: 2026-07-08 02:14:59.186700

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b5f2728ce43'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tool_catalog',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_required', sa.Boolean(), nullable=False),
    sa.Column('key_issue_url', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('auth_owner', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_catalog_key'), 'tool_catalog', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nickname')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_table('skills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('users_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('import_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_users_id'), 'skills', ['users_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('users_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('graph_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('import_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_users_id'), 'workflows', ['users_id'], unique=False)
    op.create_table('skill_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('skills_id', sa.BigInteger(), nullable=False),
    sa.Column('master_tags_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_tags_id'], ['master_tags.id'], ),
    sa.ForeignKeyConstraint(['skills_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skills_id', 'master_tags_id', name='uq_skill_tag')
    )
    op.create_index(op.f('ix_skill_tags_master_tags_id'), 'skill_tags', ['master_tags_id'], unique=False)
    op.create_index(op.f('ix_skill_tags_skills_id'), 'skill_tags', ['skills_id'], unique=False)
    op.create_table('workflow_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('workflows_id', sa.BigInteger(), nullable=False),
    sa.Column('master_tags_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_tags_id'], ['master_tags.id'], ),
    sa.ForeignKeyConstraint(['workflows_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflows_id', 'master_tags_id', name='uq_workflow_tag')
    )
    op.create_index(op.f('ix_workflow_tags_master_tags_id'), 'workflow_tags', ['master_tags_id'], unique=False)
    op.create_index(op.f('ix_workflow_tags_workflows_id'), 'workflow_tags', ['workflows_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tags_workflows_id'), table_name='workflow_tags')
    op.drop_index(op.f('ix_workflow_tags_master_tags_id'), table_name='workflow_tags')
    op.drop_table('workflow_tags')
    op.drop_index(op.f('ix_skill_tags_skills_id'), table_name='skill_tags')
    op.drop_index(op.f('ix_skill_tags_master_tags_id'), table_name='skill_tags')
    op.drop_table('skill_tags')
    op.drop_index(op.f('ix_workflows_users_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_skills_users_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tool_catalog_key'), table_name='tool_catalog')
    op.drop_table('tool_catalog')
    op.drop_table('master_tags')
    # ### end Alembic commands ###
